services:
  db:
    image: postgres:16
    container_name: jobtracker-db
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: jobtracker
      POSTGRES_PASSWORD: jobtracker
    ports:
      - "5432:5432"
    volumes:
      - jobtracker_pgdata:/var/lib/postgresql/data

volumes:
  jobtracker_pgdata:
